### ISSUE TITLE
[기능] 결제는 배민페이머니를 통해서 이루어진다.

### ISSUE THREAD

**Issue by june-777** [woowa-techcamp-2024/Team1-3K1K#77]
## 기능

주문에 대한 결제는 자체 포인트인 배민페이머니를 통해 이루어진다.

## 설명

구매자는 PG사를 통해 배민페이머니를 충전할 수 있습니다.
상품에 대한 주문은 배민페이머니만을 통해 결제할 수 있습니다.

**Comment by Dr-KoKo** [comment]
외부 PG사를 통한 결제 기능을 지원하지 않고 배민페이머니만을 통해 결제할 수 있게 변경되었습니다.
(외부 서버와 통신없이 결제를 진행할 수 있기 때문에) 주문과 동시에 결제를 진행하는 것으로 변경되었습니다.

따라서 현재 이슈는 #69 에서 같이 진행하도록 하겠습니다.
