### ISSUE TITLE
[기능] 점주 음식 상품 등록

### ISSUE THREAD

**Issue by june-777** [woowa-techcamp-2024/Team1-3K1K#8]
[유저스토리: 점주는 음식 상품을 게시할 수 있다](https://github.com/woowa-techcamp-2024/Team1-3K1K/wiki/%EC%9A%94%EA%B5%AC%EC%82%AC%ED%95%AD-%EC%A0%95%EC%9D%98%EC%84%9C#%EC%9C%A0%EC%A0%80-%EC%8A%A4%ED%86%A0%EB%A6%AC-%EC%A0%90%EC%A3%BC%EB%8A%94-%EC%9D%8C%EC%8B%9D-%EC%83%81%ED%92%88%EC%9D%84-%EA%B2%8C%EC%8B%9C%ED%95%A0-%EC%88%98-%EC%9E%88%EB%8B%A4-%EC%A0%90-4)

**Comment by kimhyun5u** [comment]
음식 상품과 상품의 옵션, 수량이 정확히 들어가야한다.

**Comment by june-777** [comment]
https://github.com/woowa-techcamp-2024/Team1-3K1K/pull/51

해당 PR에서 완료했습니다.
